@echo off
echo Starting Regal Movie Scheduler Setup...
if not exist "venv" (
    echo Creating virtual environment...
    python -m venv venv
)
echo Activating environment...
call venv\Scripts\activate
echo Checking dependencies...
pip install -r requirements.txt
echo Launching Application...
streamlit run regal_pro.py
pause